### ISSUE TITLE
Setting up Probot-owners

### ISSUE THREAD

**Issue by electricmind007** [probot/owners#17]
I have tried to setup probot-owners by installing the plugin from github.com/apps/owners. After installation, I have created a OWNERS file in the root of the directory in the master branch. I have given "@github_username **/*" in the OWNERS file. After that I have created a pull request with a text file in one of the folder inside master branch of the repository from a different username. In the new pull request, i could not see my name in the reviewers list.

Please check and let me know whether it is a bug or known issue or any mistake from my side in configuring the probot-owners.

**Comment by bkeepers** [comment]
Hey @electricmind007. You can see owners in action on https://github.com/probot/test/pull/14. Currently it only CCs reviewers because the reviews API was not available when this was first written.

I'm not sure why it's not working for you, but with the addition of the `CODEOWNERS` feature on GitHub, this app has become low priority for me. PRs for improvements are welcome.
