### ISSUE TITLE
Question: OWNERS vs CODEOWNERS

### ISSUE THREAD

**Issue by rallytime** [probot/owners#18]
I was looking into this probot project to `@mention` owners in Pull Requests as defined in GitHub's [CODEOWNERS](https://help.github.com/articles/about-codeowners/) file. I set up the CODEOWNERS file hoping to get teams we've defined to be flagged for pull request reviews automatically by GitHub. Our code owners file is [here](https://github.com/saltstack/salt/blob/develop/.github/CODEOWNERS).

Unfortunately, I didn't realize the teams must be given write-access in order to have GitHub automatically assign a team for reviews. We don't want to do this at our org, so I am looking for an alternative. Enter `probot-owners`! 

I was hoping to use probot-owners to ping the teams we've defined based on the rules we've already set up in CODEOWNERS.

It isn't apparent to me, but can CODEOWNERS be used instead of [OWNERS](https://github.com/bkeepers/OWNERS)? I am happy to change the name of the file if that is all that is needed, or I can of course look into changing the syntax as needed as well. It looks like the syntax is the similar, but I am not 100% sure. What is the difference and why are there two ways to do define this file, while they have the general same idea?

I'd be happy to add some documentation to help others based on the discussion here.

**Comment by bkeepers** [comment]
Hey @rallytime, this app doesn't support `CODEOWNERS`. 

> I am happy to change the name of the file if that is all that is needed, or I can of course look into changing the syntax as needed as well. It looks like the syntax is the similar, but I am not 100% sure. What is the difference and why are there two ways to do define this file, while they have the general same idea?

This project was released before the `CODEOWNERS` support was added to GitHub. Unfortunately, the team that worked on that feature decided to define a new file format. I didn't follow it very closely, so I'm not exactly sure the reasons why.

Due to `CODEOWNERS` support being added to GitHub, this project isn't a high priority for me at the moment, but pull requests are welcome to improve the code or documentation.

**Comment by rallytime** [comment]
Hi @bkeepers - OK that sounds goods. That answers all of my questions, so I will go ahead an close this. Thank you!
