### ISSUE TITLE
Add ability to parse issue body for links to code

### ISSUE THREAD

**Issue by patcon** [probot/owners#8]
Was trying to think how to make this useful for issues as well. The thought was that often an issue, even if there's no code yet, might link to certain lines of code in the repo. Probot could parse that and operate as if the linked lines _are_ changed lines.

Might also worked for linked documentation (headers or full files). (We use github for lots of meta, and so often are discussing and linking docs.)

Good idea? Bad idea? :)

**Comment by bkeepers** [comment]
That's a cool idea. I'm not sure how useful it would be, but it'd be cool to experiment.

> Was trying to think how to make this useful for issues as well.

This might belong in a different plugin, but I was wondering about adding the ability for people/teams to subscribe to labels. It'd be a similar format to `OWNERS`, but instead of file paths, you're selecting labels you care about, then you'd get @mentioned whenever those labels are added.

**Comment by patcon** [comment]
I really like that! I think I probably agree that unix'y approach to plugins is nice. Wouldn't personally want this to become general "GitHub issues notifier" plugin :) but whatever you think best!

**Comment by bkeepers** [comment]
Given the discussion above, I think this issue is probably out of scope. I'm going to close this, but let me know if you want to discuss it more.
